name: slinkr
description: "Una aplicación para monitorear el nivel de batería y recibir alertas."
publish_to: 'none' 
version: 1.6.0+6

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  battery_plus: ^5.0.3
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  shimmer: ^3.0.0 # <-- NUEVO PAQUETE AÑADIDO

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf

        # PEGA ESTO AL FINAL DEL ARCHIVO
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"